### ISSUE TITLE
Compiler error: 'HardWire' does not name a type

### ISSUE THREAD

**Issue by kozuch** [stevstrong/LiveOV7670_STM32#1]
Hi there, the project will not compile for me. I get following error on STM32F103C8T6 (blue pill):

```
Arduino: 1.8.5 (Windows 7), Vývojová deska: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), Serial, 72Mhz (Normal), Smallest (default)"

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp:9:1: error: 'HardWire' does not name a type

 HardWire mWire(2);

 ^

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp: In member function 'void CameraOV7670Registers::init()':

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp:14:3: error: 'mWire' was not declared in this scope

   mWire.begin();

   ^

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp: In member function 'bool CameraOV7670Registers::setRegister(uint8_t, uint8_t)':

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp:47:3: error: 'mWire' was not declared in this scope

   mWire.beginTransmission(i2cAddress);

   ^

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp: In member function 'uint8_t CameraOV7670Registers::readRegister(uint8_t)':

C:\Users\Jack\Documents\Arduino\libraries\LiveOV7670_STM32\CameraOV7670Registers.cpp:66:3: error: 'mWire' was not declared in this scope

   mWire.beginTransmission(i2cAddress);

   ^

Byly nalezené násobné knihovny "Wire.h"
 Used: C:\Users\Jack\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2018.7.2\libraries\Wire
 Unused: C:\Users\Jack\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2018.7.2\libraries\WireSlave
exit status 1
Nastala chyba při kompilaci u desky Generic STM32F103C series.

```
Can you help me please? I tried downloading and including some a HardWire library but then had an unmet dependency which I did not pursue yet.

Tried to use this: http://downloads.arduino.cc/libraries/github.com/thexeno/HardWire-1.0.2.zip

**Comment by kozuch** [comment]
Fixed by changing HardWire mWire(2); to TwoWire mWire(2);

Now I get error 4 (other error) at mWire.endTransmission() in setRegister function. mWire.write reports 1 byte written for both addr and val.

**Comment by stevstrong** [comment]
Please post the complete error messages.

**Comment by kozuch** [comment]
It now compiles without error, I get the error 4 value at runtime by printing it to serial - I put logging in CameraOV7670Registers.cpp in bool CameraOV7670Registers::setRegister(uint8_t addr, uint8_t val) function. mWire.endTransmission() simply returns 4 instead of 0. I guess this is an I2C problem. I am not sure if my camera is not dead, but I have 2 of them and both giving the same error. I think I connected everything correctly, additionally tried on camera the RESET pin to 3.3V and PWDN to ground, did not help.

I have a little different camera module than is usual - my camera is similar to the image on the left here, while the camera from the various videos is usually the one on the right: https://forum.arduino.cc/index.php?topic=535819.0

Exact photos of my camera:
https://photos.app.goo.gl/vUySrQZJQJDwMZvx5

**Comment by stevstrong** [comment]
I will check this soon.

**Comment by kozuch** [comment]
Thanks, but you don't have to any more. The problem was you used i2c bus #2 in code but your pin wiring uses bus #1. This code change fixes it:

TwoWire mWire(1);

Now the camera inits already.

**Comment by stevstrong** [comment]
https://github.com/stevstrong/LiveOV7670_STM32/commit/9829eaff253b68effd41e675ccfc78cc3fd03ff7 should fix it.

**Comment by SamTmp11** [comment]
good morning all
 ikeep getting this message on verifiying and maybe someone can help

thanks 


C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:31:1: error: 'HardWire' does not name a type
   31 | HardWire HWire(2, I2C_FAST_MODE);
      | ^~~~~~~~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino: In function 'void setup()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:59:24: error: 'AFIO_DEBUG_SW_ONLY' was not declared in this scope
   59 |   afio_cfg_debug_ports(AFIO_DEBUG_SW_ONLY);                     //Connects PB3 and PB4 to output function.
      |                        ^~~~~~~~~~~~~~~~~~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:59:3: error: 'afio_cfg_debug_ports' was not declared in this scope
   59 |   afio_cfg_debug_ports(AFIO_DEBUG_SW_ONLY);                     //Connects PB3 and PB4 to output function.
      |   ^~~~~~~~~~~~~~~~~~~~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:78:3: error: 'HWire' was not declared in this scope; did you mean 'Wire'?
   78 |   HWire.begin();                                                //Start the I2C as master
      |   ^~~~~
      |   Wire
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino: In function 'void loop()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:113:5: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
  113 |     TIMER4_BASE->CCR1 = channel_3;                              //Set the throttle receiver input pulse to the ESC 1 output pulse.
      |     ^~~~~~~~~~~
      |     TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:119:5: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
  119 |     TIMER4_BASE->CCR1 = 1000;                                   //Set the ESC 1 output to 1000us to disable the motor.
      |     ^~~~~~~~~~~
      |     TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino: In function 'void gyro_signalen()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\YMFC-32_Setup_ver-1a.ino:210:3: error: 'HWire' was not declared in this scope; did you mean 'Wire'?
  210 |   HWire.beginTransmission(gyro_address);                       //Start communication with the gyro.
      |   ^~~~~
      |   Wire
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino: In function 'void check_motor_vibrations()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino:39:9: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   39 |         TIMER4_BASE->CCR1 = channel_3;                                                 //Set the ESC 1 output pulse equal to the throttle input.
      |         ^~~~~~~~~~~
      |         TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino:45:9: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   45 |         TIMER4_BASE->CCR1 = 1000;                                                      //Keep the ESC 1 pulse at 1000us.
      |         ^~~~~~~~~~~
      |         TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino:51:9: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   51 |         TIMER4_BASE->CCR1 = 1000;                                                      //Keep the ESC 1 pulse at 1000us.
      |         ^~~~~~~~~~~
      |         TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino:57:9: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   57 |         TIMER4_BASE->CCR1 = 1000;                                                      //Keep the ESC 1 pulse at 1000us.
      |         ^~~~~~~~~~~
      |         TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\check_motor_vibrations.ino:63:9: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   63 |         TIMER4_BASE->CCR1 = channel_3;                                                 //Set the ESC 1 output pulse equal to the throttle input.
      |         ^~~~~~~~~~~
      |         TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\i2c_scanner.ino: In function 'void i2c_scanner()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\i2c_scanner.ino:10:5: error: 'HWire' was not declared in this scope; did you mean 'Wire'?
   10 |     HWire.beginTransmission(address);
      |     ^~~~~
      |     Wire
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_1()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:2:23: error: base operand of '->' is not a pointer
    2 |   if (0b1 & GPIOA_BASE->IDR  >> 0) {                     //If the receiver channel 1 input pulse on A0 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:3:23: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
    3 |     channel_1_start = TIMER2_BASE->CCR1;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:4:26: error: 'TIMER_CCER_CC1P' was not declared in this scope; did you mean 'TIM_CCER_CC1P'?
    4 |     TIMER2_BASE->CCER |= TIMER_CCER_CC1P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC1P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:7:17: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
    7 |     channel_1 = TIMER2_BASE->CCR1 - channel_1_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:9:27: error: 'TIMER_CCER_CC1P' was not declared in this scope; did you mean 'TIM_CCER_CC1P'?
    9 |     TIMER2_BASE->CCER &= ~TIMER_CCER_CC1P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC1P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_2()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:14:23: error: base operand of '->' is not a pointer
   14 |   if (0b1 & GPIOA_BASE->IDR >> 1) {                      //If the receiver channel 2 input pulse on A1 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:15:23: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   15 |     channel_2_start = TIMER2_BASE->CCR2;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:16:26: error: 'TIMER_CCER_CC2P' was not declared in this scope; did you mean 'TIM_CCER_CC2P'?
   16 |     TIMER2_BASE->CCER |= TIMER_CCER_CC2P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC2P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:19:17: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   19 |     channel_2 = TIMER2_BASE->CCR2 - channel_2_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:21:27: error: 'TIMER_CCER_CC2P' was not declared in this scope; did you mean 'TIM_CCER_CC2P'?
   21 |     TIMER2_BASE->CCER &= ~TIMER_CCER_CC2P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC2P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_3()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:26:23: error: base operand of '->' is not a pointer
   26 |   if (0b1 & GPIOA_BASE->IDR >> 2) {                      //If the receiver channel 3 input pulse on A2 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:27:23: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   27 |     channel_3_start = TIMER2_BASE->CCR3;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:28:26: error: 'TIMER_CCER_CC3P' was not declared in this scope; did you mean 'TIM_CCER_CC3P'?
   28 |     TIMER2_BASE->CCER |= TIMER_CCER_CC3P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC3P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:31:17: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   31 |     channel_3 = TIMER2_BASE->CCR3 - channel_3_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:33:27: error: 'TIMER_CCER_CC3P' was not declared in this scope; did you mean 'TIM_CCER_CC3P'?
   33 |     TIMER2_BASE->CCER &= ~TIMER_CCER_CC3P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC3P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_4()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:38:23: error: base operand of '->' is not a pointer
   38 |   if (0b1 & GPIOA_BASE->IDR >> 3) {                      //If the receiver channel 4 input pulse on A3 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:39:23: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   39 |     channel_4_start = TIMER2_BASE->CCR4;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:40:26: error: 'TIMER_CCER_CC4P' was not declared in this scope; did you mean 'TIM_CCER_CC4P'?
   40 |     TIMER2_BASE->CCER |= TIMER_CCER_CC4P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC4P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:43:17: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   43 |     channel_4 = TIMER2_BASE->CCR4 - channel_4_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:45:27: error: 'TIMER_CCER_CC4P' was not declared in this scope; did you mean 'TIM_CCER_CC4P'?
   45 |     TIMER2_BASE->CCER &= ~TIMER_CCER_CC4P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC4P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_5()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:50:23: error: base operand of '->' is not a pointer
   50 |   if (0b1 & GPIOA_BASE->IDR >> 6) {                      //If the receiver channel 5 input pulse on A6 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:51:23: error: 'TIMER3_BASE' was not declared in this scope; did you mean 'TIM3_BASE'?
   51 |     channel_5_start = TIMER3_BASE->CCR1;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM3_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:52:26: error: 'TIMER_CCER_CC1P' was not declared in this scope; did you mean 'TIM_CCER_CC1P'?
   52 |     TIMER3_BASE->CCER |= TIMER_CCER_CC1P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC1P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:55:17: error: 'TIMER3_BASE' was not declared in this scope; did you mean 'TIM3_BASE'?
   55 |     channel_5 = TIMER3_BASE->CCR1 - channel_5_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM3_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:57:27: error: 'TIMER_CCER_CC1P' was not declared in this scope; did you mean 'TIM_CCER_CC1P'?
   57 |     TIMER3_BASE->CCER &= ~TIMER_CCER_CC1P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC1P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino: In function 'void handler_channel_6()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:62:23: error: base operand of '->' is not a pointer
   62 |   if (0b1 & GPIOA_BASE->IDR >> 7) {                      //If the receiver channel 6 input pulse on A7 is high.
      |                       ^~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:63:23: error: 'TIMER3_BASE' was not declared in this scope; did you mean 'TIM3_BASE'?
   63 |     channel_6_start = TIMER3_BASE->CCR2;                 //Record the start time of the pulse.
      |                       ^~~~~~~~~~~
      |                       TIM3_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:64:26: error: 'TIMER_CCER_CC2P' was not declared in this scope; did you mean 'TIM_CCER_CC2P'?
   64 |     TIMER3_BASE->CCER |= TIMER_CCER_CC2P;                //Change the input capture mode to the falling edge of the pulse.
      |                          ^~~~~~~~~~~~~~~
      |                          TIM_CCER_CC2P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:67:17: error: 'TIMER3_BASE' was not declared in this scope; did you mean 'TIM3_BASE'?
   67 |     channel_6 = TIMER3_BASE->CCR2 - channel_6_start;     //Calculate the total pulse time.
      |                 ^~~~~~~~~~~
      |                 TIM3_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\input_capture_mode_handlers.ino:69:27: error: 'TIMER_CCER_CC2P' was not declared in this scope; did you mean 'TIM_CCER_CC2P'?
   69 |     TIMER3_BASE->CCER &= ~TIMER_CCER_CC2P;               //Change the input capture mode to the rising edge of the pulse.
      |                           ^~~~~~~~~~~~~~~
      |                           TIM_CCER_CC2P
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino: In function 'void timer_setup()':
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:8:3: error: 'Timer2' was not declared in this scope
    8 |   Timer2.attachCompare1Interrupt(handler_channel_1);
      |   ^~~~~~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:12:3: error: 'TIMER2_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   12 |   TIMER2_BASE->CR1 = TIMER_CR1_CEN;
      |   ^~~~~~~~~~~
      |   TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:12:22: error: 'TIMER_CR1_CEN' was not declared in this scope; did you mean 'TIM_CR1_CEN'?
   12 |   TIMER2_BASE->CR1 = TIMER_CR1_CEN;
      |                      ^~~~~~~~~~~~~
      |                      TIM_CR1_CEN
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:15:23: error: 'TIMER_DIER_CC1IE' was not declared in this scope; did you mean 'TIM_DIER_CC1IE'?
   15 |   TIMER2_BASE->DIER = TIMER_DIER_CC1IE | TIMER_DIER_CC2IE | TIMER_DIER_CC3IE | TIMER_DIER_CC4IE;
      |                       ^~~~~~~~~~~~~~~~
      |                       TIM_DIER_CC1IE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:15:42: error: 'TIMER_DIER_CC2IE' was not declared in this scope; did you mean 'TIM_DIER_CC2IE'?
   15 |   TIMER2_BASE->DIER = TIMER_DIER_CC1IE | TIMER_DIER_CC2IE | TIMER_DIER_CC3IE | TIMER_DIER_CC4IE;
      |                                          ^~~~~~~~~~~~~~~~
      |                                          TIM_DIER_CC2IE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:15:61: error: 'TIMER_DIER_CC3IE' was not declared in this scope; did you mean 'TIM_DIER_CC3IE'?
   15 |   TIMER2_BASE->DIER = TIMER_DIER_CC1IE | TIMER_DIER_CC2IE | TIMER_DIER_CC3IE | TIMER_DIER_CC4IE;
      |                                                             ^~~~~~~~~~~~~~~~
      |                                                             TIM_DIER_CC3IE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:15:80: error: 'TIMER_DIER_CC4IE' was not declared in this scope; did you mean 'TIM_DIER_CC4IE'?
   15 |   TIMER2_BASE->DIER = TIMER_DIER_CC1IE | TIMER_DIER_CC2IE | TIMER_DIER_CC3IE | TIMER_DIER_CC4IE;
      |                                                                                ^~~~~~~~~~~~~~~~
      |                                                                                TIM_DIER_CC4IE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:19:23: error: 'TIMER_CCER_CC1E' was not declared in this scope; did you mean 'TIM_CCER_CC1E'?
   19 |   TIMER2_BASE->CCER = TIMER_CCER_CC1E | TIMER_CCER_CC2E | TIMER_CCER_CC3E | TIMER_CCER_CC4E;
      |                       ^~~~~~~~~~~~~~~
      |                       TIM_CCER_CC1E
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:19:41: error: 'TIMER_CCER_CC2E' was not declared in this scope; did you mean 'TIM_CCER_CC2E'?
   19 |   TIMER2_BASE->CCER = TIMER_CCER_CC1E | TIMER_CCER_CC2E | TIMER_CCER_CC3E | TIMER_CCER_CC4E;
      |                                         ^~~~~~~~~~~~~~~
      |                                         TIM_CCER_CC2E
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:19:59: error: 'TIMER_CCER_CC3E' was not declared in this scope; did you mean 'TIM_CCER_CC3E'?
   19 |   TIMER2_BASE->CCER = TIMER_CCER_CC1E | TIMER_CCER_CC2E | TIMER_CCER_CC3E | TIMER_CCER_CC4E;
      |                                                           ^~~~~~~~~~~~~~~
      |                                                           TIM_CCER_CC3E
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:19:77: error: 'TIMER_CCER_CC4E' was not declared in this scope; did you mean 'TIM_CCER_CC4E'?
   19 |   TIMER2_BASE->CCER = TIMER_CCER_CC1E | TIMER_CCER_CC2E | TIMER_CCER_CC3E | TIMER_CCER_CC4E;
      |                                                                             ^~~~~~~~~~~~~~~
      |                                                                             TIM_CCER_CC4E
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:24:3: error: 'Timer3' was not declared in this scope
   24 |   Timer3.attachCompare1Interrupt(handler_channel_5);
      |   ^~~~~~
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:26:3: error: 'TIMER3_BASE' was not declared in this scope; did you mean 'TIM3_BASE'?
   26 |   TIMER3_BASE->CR1 = TIMER_CR1_CEN;
      |   ^~~~~~~~~~~
      |   TIM3_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:65:5: error: 'TIMER4_BASE' was not declared in this scope; did you mean 'TIM2_BASE'?
   65 |     TIMER4_BASE->CR1 = TIMER_CR1_CEN | TIMER_CR1_ARPE;
      |     ^~~~~~~~~~~
      |     TIM2_BASE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:65:40: error: 'TIMER_CR1_ARPE' was not declared in this scope; did you mean 'TIM_CR1_ARPE'?
   65 |     TIMER4_BASE->CR1 = TIMER_CR1_CEN | TIMER_CR1_ARPE;
      |                                        ^~~~~~~~~~~~~~
      |                                        TIM_CR1_ARPE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:70:41: error: 'TIMER_CCMR1_OC1PE' was not declared in this scope; did you mean 'TIM_CCMR1_OC1PE'?
   70 |     TIMER4_BASE->CCMR1 = (0b110 << 4) | TIMER_CCMR1_OC1PE |(0b110 << 12) | TIMER_CCMR1_OC2PE;
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         TIM_CCMR1_OC1PE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:70:76: error: 'TIMER_CCMR1_OC2PE' was not declared in this scope; did you mean 'TIM_CCMR1_OC2PE'?
   70 |     TIMER4_BASE->CCMR1 = (0b110 << 4) | TIMER_CCMR1_OC1PE |(0b110 << 12) | TIMER_CCMR1_OC2PE;
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            TIM_CCMR1_OC2PE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:71:41: error: 'TIMER_CCMR2_OC3PE' was not declared in this scope; did you mean 'TIM_CCMR2_OC3PE'?
   71 |     TIMER4_BASE->CCMR2 = (0b110 << 4) | TIMER_CCMR2_OC3PE |(0b110 << 12) | TIMER_CCMR2_OC4PE;
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         TIM_CCMR2_OC3PE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:71:76: error: 'TIMER_CCMR2_OC4PE' was not declared in this scope; did you mean 'TIM_CCMR2_OC4PE'?
   71 |     TIMER4_BASE->CCMR2 = (0b110 << 4) | TIMER_CCMR2_OC3PE |(0b110 << 12) | TIMER_CCMR2_OC4PE;
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            TIM_CCMR2_OC4PE
C:\Users\PC\Downloads\YMFC-32 (1)\YMFC-32_Setup_ver-1a\timer_setup.ino:82:18: error: 'PWM' was not declared in this scope; did you mean 'PWR'?
   82 |     pinMode(PB6, PWM);
      |                  ^~~
      |                  PWR

exit status 1

Compilation error: 'HardWire' does not name a type

**Comment by stevstrong** [comment]
It seems that you are not using my STM32 repository.
Do you build and compile with Arduino IDE? Which target have you chosen?
