### ISSUE TITLE
Camera won't initialize - any ideas?

### ISSUE THREAD

**Issue by hoffberg** [stevstrong/LiveOV7670_STM32#2]
I am trying to duplicate this project.  I have duplicated the circuit using a generic Blue Pill, SPI TFT and OV7670 (no FIFO).  

After downloading the code, the TFT initializes, but it seems that the program hangs when the CameraOV7670Registers.cpp function is called for the first time.  My gut feeling is that it has something to do with the SPI bus...  I have replaced the 'HardWire mWire(2);' line with 'TwoWire mWire(1);' as the previous comments stated.

I have added some debugging commands that print out to the TFT screen, so I am confident that this portion works as intended.

My previous experience with the OV7670 was to get it working with the Arduino UNO (as described elsewhere on the internet).  I believe that my camera module is functional, and have also tried 2 others.

At one point I did actually receive the red screen with the camera failure message, but I have not been able to duplicate it.  

My next step might be to try to recreate the other project (STM32_OV7670), but I was hoping that I could just jump to this one directly.

So, do you have any suggestions as to what might be tripping me up?  Any debugging suggestions (I have limited test equipment - no oscilloscope nor logic analyzer)?

Any help that you could provide would be appreciated.

**Comment by stevstrong** [comment]
Which CPP function do yo mean that is hangs when called?
Have you tried higher prescaler values here: https://github.com/stevstrong/LiveOV7670_STM32/blob/master/examples/LiveOV7670stm32/LiveOV7670stm32.ino#L30 ?

**Comment by hoffberg** [comment]
Yes - it seems that as soon as CameraOV7670Reggisters.cpp is called (I have added another function to it for debugging, so I am not calling init first), it crashes.  I am guessing at this point that it is the 'TwoWire mWire(1);' line (first real function in the file).

I set the prescaler to 10, but it did not seem to make a difference.

I was just about to start to give the other program (STM32_OV7670) a try [UPDATE - I now realize that this was your code to read a power meter, so it does not look like it is going to work for me, including the fact that there is no OV7670.h file].

**Comment by stevstrong** [comment]
`CameraOV7670Reggisters.cpp` is a file, not a function.
So again, which function call hangs?
Does the TFT work? Can you see on the display "Setting up the camera..."?
Did you connect 3.3kOhm (max. 5k) pull-up resistors between SCL and SDA and 3.3V?

**Comment by hoffberg** [comment]
I am somewhat hampered by my programming ability...  I will have to figure out exactly where it stops working.

The TFT is functioning as expected.  I get the blue screen and a couple of lines of status.  I will have to reverse my changes to tell you exactly which is the last message.

I DID NOT connect the 3.3KOhm resistor between SCL, SDA and 3.3V...  I guess you are saying is that the pull up resistors on the SCL and SDA are not optional :) - I will be adding them now.  

I appreciate your help.

**Comment by stevstrong** [comment]
As long the camera board does not have the pull-ups, you have to provide them. It is mandatory.

**Comment by stevstrong** [comment]
Just committed https://github.com/stevstrong/LiveOV7670_STM32/commit/9829eaff253b68effd41e675ccfc78cc3fd03ff7 to fix wrong wire instance.

**Comment by hoffberg** [comment]
I think that this issue can be closed as non-discrepant ('User Error').  The camera now displays to the screen (although the display is a bit garbled, it might be a bad solder joint or the camera data bus might have an error.  

(The middle of the diplay is black, with garbled data on each side, and the colors seem off, and every other line is black.  I seem to recall somewhere that I read that different flavors of the TFT display might have different color ordering.)

I would recommend at some point, an updated the comment be added to the LiveOV7670stm32.ino file to include a reminder to also include "pull-up resistors (3.3K Ohm to 3.3V) on I2C Clock and I2C Data if the camera board does not already include them."  As far as I can tell, no where else is the circuit schematic described.

Thanks for your help.

**Comment by stevstrong** [comment]
Well, the `README.md` already mentioned to connect resistors on the I2C lines, which I think is pretty obvious for anyone dealing with I2C. I now corrected the values to 3k3.
